[2024-06-14T16:29:28.555+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T16:29:28.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.insert_into_db_table scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2024-06-14T16:29:28.863+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.insert_into_db_table scheduled__2024-06-07T00:00:00+00:00 [queued]>
[2024-06-14T16:29:28.864+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-06-14T16:29:28.989+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): insert_into_db_table> on 2024-06-07 00:00:00+00:00
[2024-06-14T16:29:29.011+0000] {standard_task_runner.py:63} INFO - Started process 1404 to run task
[2024-06-14T16:29:29.049+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'insert_into_db_table', 'scheduled__2024-06-07T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp3fe13op7']
[2024-06-14T16:29:29.079+0000] {standard_task_runner.py:91} INFO - Job 266: Subtask insert_into_db_table
[2024-06-14T16:29:29.665+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.insert_into_db_table scheduled__2024-06-07T00:00:00+00:00 [running]> on host 6078ceb33835
[2024-06-14T16:29:30.959+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='insert_into_db_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-07T00:00:00+00:00'
[2024-06-14T16:29:30.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T16:29:30.985+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/database/populate_db.py:26 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-14T16:29:31.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T16:29:31.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/database/populate_db.py", line 28, in insert_into_db_table
    data = input_clean_data.to_records(index=False).tolist()
AttributeError: 'str' object has no attribute 'to_records'
[2024-06-14T16:29:31.045+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=insert_into_db_table, run_id=scheduled__2024-06-07T00:00:00+00:00, execution_date=20240607T000000, start_date=20240614T162928, end_date=20240614T162931
[2024-06-14T16:29:31.630+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 266 for task insert_into_db_table ('str' object has no attribute 'to_records'; 1404)
[2024-06-14T16:29:31.705+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T16:29:31.749+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T16:29:31.762+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
