[2024-06-17T04:03:41.748+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T04:03:41.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-17T04:03:20+00:00 [queued]>
[2024-06-17T04:03:41.819+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-17T04:03:20+00:00 [queued]>
[2024-06-17T04:03:41.820+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-17T04:03:41.848+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-06-17 04:03:20+00:00
[2024-06-17T04:03:41.858+0000] {standard_task_runner.py:63} INFO - Started process 483 to run task
[2024-06-17T04:03:41.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'manual__2024-06-17T04:03:20+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpm7ovplqc']
[2024-06-17T04:03:41.871+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask validator
[2024-06-17T04:03:41.959+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-17T04:03:20+00:00 [running]> on host fa4d239664b0
[2024-06-17T04:03:42.649+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T04:03:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T04:03:20+00:00'
[2024-06-17T04:03:42.652+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T04:03:42.653+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-17T04:03:42.706+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/validate/validate.py:14 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-17T04:03:43.178+0000] {python.py:237} INFO - Done. Returned value was: dict_keys(['Ammonia_NH_emissions', 'Black_carbon_BC_emissions', 'Carbon_monoxide_CO_emissions', 'Code', 'Entity', 'Nitrogen_oxide_NOx', 'Non_methane_volatile_organic_compounds_NMVOC_emissions', 'Organic_carbon_OC_emissions', 'Sulphur_dioxide_SO_emissions', 'Year'])
[2024-06-17T04:03:43.180+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T04:03:43.204+0000] {xcom.py:675} ERROR - Object of type dict_keys is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-06-17T04:03:43.209+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'dict_keys'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_keys is not JSON serializable
[2024-06-17T04:03:43.259+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=manual__2024-06-17T04:03:20+00:00, execution_date=20240617T040320, start_date=20240617T040341, end_date=20240617T040343
[2024-06-17T04:03:43.311+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task validator (Object of type dict_keys is not JSON serializable; 483)
[2024-06-17T04:03:43.377+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T04:03:43.459+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T04:03:43.464+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
