[2024-06-16T17:51:41.475+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T17:51:41.536+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:43:10+00:00 [queued]>
[2024-06-16T17:51:41.552+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:43:10+00:00 [queued]>
[2024-06-16T17:51:41.553+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-06-16T17:51:41.603+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-06-16 17:43:10+00:00
[2024-06-16T17:51:41.637+0000] {standard_task_runner.py:63} INFO - Started process 5286 to run task
[2024-06-16T17:51:41.657+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'manual__2024-06-16T17:43:10+00:00', '--job-id', '516', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpke5nxi37']
[2024-06-16T17:51:41.666+0000] {standard_task_runner.py:91} INFO - Job 516: Subtask validator
[2024-06-16T17:51:41.893+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T17:43:10+00:00 [running]> on host 333385971b19
[2024-06-16T17:51:43.266+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T17:43:10+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T17:43:10+00:00'
[2024-06-16T17:51:43.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T17:51:43.271+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-16T17:51:43.345+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/validate/validate.py:14 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-16T17:51:44.180+0000] {python.py:237} INFO - Done. Returned value was: yes
[2024-06-16T17:51:44.181+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T17:51:44.197+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 474, in _execute_task
    raise AirflowException(
airflow.exceptions.AirflowException: Returned output was type <class 'str'> expected dictionary for multiple_outputs
[2024-06-16T17:51:44.203+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=manual__2024-06-16T17:43:10+00:00, execution_date=20240616T174310, start_date=20240616T175141, end_date=20240616T175144
[2024-06-16T17:51:44.225+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 516 for task validator (Returned output was type <class 'str'> expected dictionary for multiple_outputs; 5286)
[2024-06-16T17:51:44.257+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T17:51:44.302+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T17:51:44.305+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
