[2024-06-16T19:56:04.846+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T19:56:04.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T19:55:41+00:00 [queued]>
[2024-06-16T19:56:04.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T19:55:41+00:00 [queued]>
[2024-06-16T19:56:04.915+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-16T19:56:04.937+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-06-16 19:55:41+00:00
[2024-06-16T19:56:04.948+0000] {standard_task_runner.py:63} INFO - Started process 6538 to run task
[2024-06-16T19:56:04.956+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'manual__2024-06-16T19:55:41+00:00', '--job-id', '548', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpljf_x5n4']
[2024-06-16T19:56:04.960+0000] {standard_task_runner.py:91} INFO - Job 548: Subtask validator
[2024-06-16T19:56:05.057+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator manual__2024-06-16T19:55:41+00:00 [running]> on host 333385971b19
[2024-06-16T19:56:05.913+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T19:55:41+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T19:55:41+00:00'
[2024-06-16T19:56:05.916+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T19:56:05.919+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-16T19:56:05.995+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/validate/validate.py:14 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-16T19:56:06.638+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T19:56:06.639+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/validate/validate.py", line 15, in validator
    return input_clean_data.tolist()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tolist'
[2024-06-16T19:56:06.680+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=manual__2024-06-16T19:55:41+00:00, execution_date=20240616T195541, start_date=20240616T195604, end_date=20240616T195606
[2024-06-16T19:56:06.712+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 548 for task validator ('DataFrame' object has no attribute 'tolist'; 6538)
[2024-06-16T19:56:06.786+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-16T19:56:06.868+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T19:56:06.873+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
