[2024-06-14T16:21:46.246+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T16:21:46.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-06-14T16:21:46.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Air_pollution_data_pipeline.validator scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-06-14T16:21:46.817+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-14T16:21:46.993+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): validator> on 2024-05-30 00:00:00+00:00
[2024-06-14T16:21:47.038+0000] {standard_task_runner.py:63} INFO - Started process 545 to run task
[2024-06-14T16:21:47.075+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Air_pollution_data_pipeline', 'validator', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmps6x2hy3l']
[2024-06-14T16:21:47.109+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask validator
[2024-06-14T16:21:47.494+0000] {task_command.py:426} INFO - Running <TaskInstance: Air_pollution_data_pipeline.validator scheduled__2024-05-30T00:00:00+00:00 [running]> on host 6078ceb33835
[2024-06-14T16:21:48.071+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='khalid' AIRFLOW_CTX_DAG_ID='Air_pollution_data_pipeline' AIRFLOW_CTX_TASK_ID='validator' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-06-14T16:21:48.087+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T16:21:48.089+0000] {validate.py:11} INFO - stating data validation/transformation process
[2024-06-14T16:21:48.123+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/validate/validate.py:14 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2024-06-14T16:21:48.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T16:21:48.181+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/validate/validate.py", line 17, in validator
    exp_col_names = input_clean_data.columns.sort()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5953, in sort
    raise TypeError("cannot sort an Index object in-place, use sort_values instead")
TypeError: cannot sort an Index object in-place, use sort_values instead
[2024-06-14T16:21:48.243+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Air_pollution_data_pipeline, task_id=validator, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240614T162146, end_date=20240614T162148
[2024-06-14T16:21:48.327+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 73 for task validator (cannot sort an Index object in-place, use sort_values instead; 545)
[2024-06-14T16:21:48.447+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T16:21:48.504+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
