[2024-06-17T04:28:00.238+0000] {scheduler_job_runner.py:843} ERROR - Executor reports task instance <TaskInstance: Air_pollution_data_pipeline.generate_summary manual__2024-06-17T04:21:22+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
